[package]
name = "connect_4_square"
version = "0.1.0"
authors = ["27kUltraHd <nhaison@pdx.edu>"]
edition = "2018"

[dependencies]
rand = "0.7"
ws = "*"
nickel = "*"
mustache = "*"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }